### ISSUE TITLE
Check Begin / End for Deputy and Ticket

### ISSUE THREAD

**Issue by konne** [florianeck/redmine_auto_deputy#11]
Hi,
If a user is not available for example from the 01th of Aug to the 08th of Aug and somebody tries to assign a ticket that start after the 08th the assigment should be possible and not routed to the deputy.
Why. If somebody plan that resource now for a task after his holiday this ticket should not routed to the deputy and direct to the user.
So the new rule should be. No deputy rule if the TicketBegin is in the future and the TicketBegin is not in a not available timeslot.

bye Konrad

**Comment by florianeck** [comment]
according to your example and after looking at the code it looks to me that the problem is the time range and how it the availability is determined.

Example: 
```
user.ununavailable_from = Date.new(2016,8,1)
user.ununavailable_to = Date.new(2016,8,8)
user.available_at?(Date.new(2016,8,8)) #=> false
```

maybe this scenario should be true? So we exclude the last day. What do you think?

**Comment by florianeck** [comment]
> So if the ticket startdate is > today() check user.available_at?(ticket.startdate) otherwise take user.available_at?(today())

@konne See https://github.com/florianeck/redmine_auto_deputy/commit/70901e11027c68c28127d9612f2ff9aa655a9020#diff-9bd61d8e7dc09415a22cb2bd8f0d7fe6R12

This is the condition you described above.

**Comment by konne** [comment]
@florianeck thats wrong you check the due_date but the start_date has to be checked.

**Comment by florianeck** [comment]
@konne ok so thats a conceptual mistake in the first place, i did not see that. 
Please confirm (Reference date must always be start date, s. https://github.com/florianeck/redmine_auto_deputy/blob/master/lib/redmine_auto_deputy/issue_extension.rb#L12) and i change that

**Comment by konne** [comment]
yes, because this make sense. If the ticket for example starts in 2 weeks and I'm at the moment on holiday this is not an issue. so confirmed, please change that line
