### ISSUE TITLE
Feature Request: Deputy in Subprojects

### ISSUE THREAD

**Issue by konne** [florianeck/redmine_auto_deputy#12]
Hi,

at the moment for each project a deputy has to defined. It should be possible to add a flag to a project that also for all subprojects of this project that don't have a own deputy definition this deputy settings of the parent project is valid.
But this has a real low prioritity.

bye Konrad

**Comment by florianeck** [comment]
In Progress here: https://github.com/florianeck/redmine_auto_deputy/pull/15
