### ISSUE TITLE
Feature Request: Warning with next possible Date for assignment

### ISSUE THREAD

**Issue by konne** [florianeck/redmine_auto_deputy#14]
At the moment if a Ticket can not assigned, it just write that it can not assigned on that possible date. Is it possible to calculate easy the next possible date for an assignment, so the warning message is more helpful?

**Comment by florianeck** [comment]
@konne we can easily display the range in with the user is not available as the user is entering that data in the first place.

**Comment by konne** [comment]
cool

**Comment by florianeck** [comment]
@konne can be checked out already, but i did not tested it on my machine in the browser yet, just the specs are rewritten

**Comment by konne** [comment]
@florianeck cool, please make this change.

**Comment by florianeck** [comment]
@konne its in master already 👍

**Comment by florianeck** [comment]
<img width="1372" alt="bildschirmfoto 2016-08-03 um 16 28 44" src="https://cloud.githubusercontent.com/assets/110351/17369145/5fac21b8-5997-11e6-95d1-8756c222d3d4.png">
