### ISSUE TITLE
absence not working with oneday

### ISSUE THREAD

**Issue by konne** [florianeck/redmine_auto_deputy#17]
Hi,
I you add an absence for example from 2016-08-12 to 2016-08-12, this is not working.

bye Konrad

**Comment by florianeck** [comment]
@konne 
- can you save the data correctly? are they shown correctly on the deputies page?
- IF yes: when you try to assign an issue to this user, does it just assign it without complaining or is it ignoring available deputies and just tells you that the issue cant be assigned at all?

**Comment by konne** [comment]
>can you save the data correctly? 

– deputy – yes / assignee - yes

> are they shown correctly on the deputies page? 

– yes correctly

>IF yes: when you try to assign an issue to this user, does it just assign it without complaining or is it ignoring available deputies and just tells you that the issue cant be assigned at all? 

– just ignores deputies and assigns to me

**Comment by florianeck** [comment]
ok thx, i'll fix this tonight and give you an update

**Comment by Qlikster** [comment]
Hi,
some update on this issue. When the absence is set to 1 calendar day, this is noit recognized as absence (see screenshot). Therefore auto assignement of tickets fails. If set to at least 2 days, the whole process works fine.

Best Regards

![image](https://cloud.githubusercontent.com/assets/21054562/17692697/6f232714-639b-11e6-8e1f-26fa2064bee9.png)

**Comment by Qlikster** [comment]
Sorry but it is not working as expected. Yet, we could refine the problem. When the absence is set to today, this is saved, but not recognized as absence, if it is a past date, this is forbidden (logical) and if it is a future date it works fine.

Best Regards

**Comment by florianeck** [comment]
Ok, thx, thats helps to fix the problem.
UPdate will be available soon

**Comment by florianeck** [comment]
@Qlikster @konne 
should work now .... otherwise please give me feedback and reopen issue.
thx
