### ISSUE TITLE
500 Internal Server Error for Redmine 3.4.6

### ISSUE THREAD

**Issue by Spongar** [florianeck/redmine_auto_deputy#21]
Plugin doesn't work with version 3.4.6-stable. An error appears:

```
Completed 500 Internal Server Error in 10ms (ActiveRecord: 3.7ms)

ActiveRecord::StatementInvalid (PG::SyntaxError: ERROR:  syntax error at or near "."
LINE 1: SELECT "roles".* FROM "roles" WHERE (`roles`.`permissions` L...
                                                    ^
: SELECT "roles".* FROM "roles" WHERE (`roles`.`permissions` LIKE '%be_deputy%')):
  plugins/redmine_auto_deputy/lib/redmine_auto_deputy/user_deputy_extension.rb:11:in `block (2 levels) in <module:UserDeputyExtension>'
  plugins/redmine_auto_deputy/app/controllers/user_deputies_controller.rb:9:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by konne** [comment]
@Spongar we usally use that plugin with easyredmine, but it should also work with normal redmine.
Did you make a migrate?

**Comment by Spongar** [comment]
> Did you make a migrate?

Yes, sure.
I solved the problem by removing all grave ( ` ) characters from SQL sections.
Maybe I'll make pull request later.

**Comment by konne** [comment]
@Spongar what database are you using. I know that this code is a little bit dirty with the direct SQL.
I use mariaDB

**Comment by Spongar** [comment]
> what database are you using

Postgres 9.6.10. Well, probably that's the reason.

**Comment by florianeck** [comment]
@Spongar yes please make a PR -  will test it on mysql then as well... i think i remember the backticks or not Postgres Syntax... it should work without them as

**Comment by Spongar** [comment]
> yes please make a PR

Done.
