### ISSUE TITLE
Plugin not working with redmine 3.4.2

### ISSUE THREAD

**Issue by Vash1990** [florianeck/redmine_auto_deputy#23]
First of all this plugin looks really promising and exactly what i wanted. Maybe i did something wrong but the assignes of newly created issues are not automatically changing. 

I setup a vacant time and a deputy for my projekt but it won't reassign any tickets.

**Comment by florianeck** [comment]
Hello and sorry for late response... could you describe more detailed whats happening?

**Comment by florianeck** [comment]
Closing due to no response.....
