### ISSUE TITLE
datepicker z level error

### ISSUE THREAD

**Issue by konne** [florianeck/redmine_auto_deputy#4]
see picture:

![pic_date_picker](https://cloud.githubusercontent.com/assets/1100969/15313726/6a6f87ec-1c0d-11e6-9cb6-ea884d71f45b.PNG)

**Comment by florianeck** [comment]
i got that one while testing as well, fixed it at least in Chrome/OSX

please report browser version and OS

**Comment by konne** [comment]
Firefox 46.01 Windows 10 64bit

**Comment by florianeck** [comment]
@konne thx i'll try to reproduce that... always that frontend stuff 😂

**Comment by florianeck** [comment]
was not reproduceable on FF/OSX, i will try again on my windows machine tonight. besides that, i added a small change that could possibly fix that already, @konne if you could try it again it would be great. 
thx in advance!
