### ISSUE TITLE
Feature Request: Manage Deputy in Roles

### ISSUE THREAD

**Issue by konne** [florianeck/redmine_auto_deputy#5]
1. that only certain users can add deputies
2. that an admin can manage deputies of other users

**Comment by florianeck** [comment]
1. Only certain users can add deputies for itself?

**Comment by konne** [comment]
1. Only certain users can add deputies for itself?
yes, if they can do it for themselfs
2. Only users that are allowed to set deputies are allowed to be set as deputies?
yes and no, we have to discuss that.

**Comment by florianeck** [comment]
OK alright,
we can reuse the Redmine Roles/Permissions for that, and then there is a small update to be made in the controller/view, as it currently always refers to `User.current` as the invoked user, but as that is only a small interface change it should not take longer than 2-3 hours including updated specs.

**Comment by florianeck** [comment]
https://github.com/florianeck/redmine_auto_deputy/pull/6
